version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: stylelint-config-standard
        versions:
          - 21.0.0
      - dependency-name: husky
        versions:
          - 5.0.9
          - 5.1.1
      - dependency-name: "@testing-library/react-hooks"
        versions:
          - 5.0.3
      - dependency-name: "@rollup/plugin-node-resolve"
        versions:
          - 11.1.0
          - 11.1.1
          - 11.2.0
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
